Repository noiapp/noi-app-android, pull requests merged in 2020-05, with the labels that each got.

#25 Add PopUp PING-PONG bluetooth fra device
  app/src/dev/java/org/dpppt/android/app/debug/DebugFragment.java
  app/src/main/res/layout/fragment_debug.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: under test

#48 Modifiche descrizioni testi
  app/src/main/res/values-it/strings.xml
Labels: enhancement, help wanted

#52 Translate Android front end labels into French
  app/src/main/res/values-fr/strings.xml
Labels: review developer

#45 adding empty line for consistency #44
  README.md
Labels: documentation, enhancement, review developer

#57 change text welcome wizard
  app/src/main/res/values-it/strings.xml
Labels: to test

#55 [UPD] versionCode from git's tag + basecode (90000000)
  app/build.gradle
Labels: review developer, to test
